#!/bin/bash
cp -Rf . /tmp/cafi-repo\
    && git checkout -f gh-pages\
    && rm -Rf *\
    && cp -Rf /tmp/cafi-repo/* .\
    && find src -name \.git -exec rm -Rf {} \;
git add .\
    && git commit -am 'updating gh-pages - automatic publish script'\
    && git push origin gh-pages\
    && git checkout -f master\
    && echo "Cafi gh-page is now in its latest revision.\n"
